apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: ns-{{ .Values.package_ns }}
  labels:
    app: nginx
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginx